/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILandLicenseRegistry,
  ILandLicenseRegistryInterface,
} from "../../TransactionContract.sol/ILandLicenseRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "_licenseId",
        type: "string",
      },
    ],
    name: "getOwnersOfCert",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_licenseId",
        type: "string",
      },
    ],
    name: "getRepresentativeOfOwners",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_licenseId",
        type: "string",
      },
    ],
    name: "getStateOfCert",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_licenseId",
        type: "string",
      },
    ],
    name: "setStateOfCertInTransaction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_licenseId",
        type: "string",
      },
    ],
    name: "setStateOfCertOutTransaction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_licenseId",
        type: "string",
      },
      {
        internalType: "address",
        name: "_newOwner",
        type: "address",
      },
    ],
    name: "transferLandOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ILandLicenseRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): ILandLicenseRegistryInterface {
    return new Interface(_abi) as ILandLicenseRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ILandLicenseRegistry {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ILandLicenseRegistry;
  }
}
