/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ILandLicenseRegistry__factory } from "./ILandLicenseRegistry__factory";
export { TransactionContract__factory } from "./TransactionContract__factory";
