/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ILandLicenseRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getOwnersOfCert"
      | "getRepresentativeOfOwners"
      | "getStateOfCert"
      | "setStateOfCertInTransaction"
      | "setStateOfCertOutTransaction"
      | "transferLandOwnership"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getOwnersOfCert",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRepresentativeOfOwners",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getStateOfCert",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setStateOfCertInTransaction",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setStateOfCertOutTransaction",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferLandOwnership",
    values: [string, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getOwnersOfCert",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRepresentativeOfOwners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStateOfCert",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStateOfCertInTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStateOfCertOutTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferLandOwnership",
    data: BytesLike
  ): Result;
}

export interface ILandLicenseRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ILandLicenseRegistry;
  waitForDeployment(): Promise<this>;

  interface: ILandLicenseRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getOwnersOfCert: TypedContractMethod<
    [_licenseId: string],
    [string[]],
    "view"
  >;

  getRepresentativeOfOwners: TypedContractMethod<
    [_licenseId: string],
    [string],
    "view"
  >;

  getStateOfCert: TypedContractMethod<[_licenseId: string], [bigint], "view">;

  setStateOfCertInTransaction: TypedContractMethod<
    [_licenseId: string],
    [void],
    "nonpayable"
  >;

  setStateOfCertOutTransaction: TypedContractMethod<
    [_licenseId: string],
    [void],
    "nonpayable"
  >;

  transferLandOwnership: TypedContractMethod<
    [_licenseId: string, _newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getOwnersOfCert"
  ): TypedContractMethod<[_licenseId: string], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRepresentativeOfOwners"
  ): TypedContractMethod<[_licenseId: string], [string], "view">;
  getFunction(
    nameOrSignature: "getStateOfCert"
  ): TypedContractMethod<[_licenseId: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "setStateOfCertInTransaction"
  ): TypedContractMethod<[_licenseId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setStateOfCertOutTransaction"
  ): TypedContractMethod<[_licenseId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferLandOwnership"
  ): TypedContractMethod<
    [_licenseId: string, _newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
