/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ILandLicenseRegistry } from "./ILandLicenseRegistry";
export type { TransactionContract } from "./TransactionContract";
